import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ProstaScanIA",
  description: "Generated by create next app",
};
 

import { ReactNode } from "react";
import React from "react";

interface CustomProps {
  children: ReactNode & {
    props?: {
      segment?: {
        metadata?: {
          navbarStyle?: string;
        };
      };
    };
  };
}
import { Navbar } from './components/Navbar';

export default function RootLayout({ children }: CustomProps) {
  let navbarColor = "";
  if (React.isValidElement(children) && children.props?.segment?.metadata) {
    navbarColor = children.props.segment.metadata.navbarStyle || "";
  }
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar color={navbarColor} />
        <main>{children}</main>
      </body>
    </html>
  );
}